#[derive(Debug, Eq, PartialEq, Copy, Clone)]
pub enum Driver {
    CarlosSainz,
    DaniilKvyat,
    DanielRicciardo,
    KimiRaikkonen,
    LewisHamilton,
    MaxVerstappen,
    NicoHulkenburg,
    KevinMagnussen,
    RomainGrosjean,
    SebastianVettel,
    SergioPerez,
    ValtteriBottas,
    EstebanOcon,
    LanceStroll,
    ArronBarnes,
    MartinGiles,
    AlexMurray,
    LucasRoth,
    IgorCorreia,
    SophieLevasseur,
    JonasSchiffer,
    AlainForest,
    JayLetourneau,
    EstoSaari,
    YasarAtiyeh,
    CallistoCalabresi,
    NaotaIzum,
    HowardClarke,
    WilhelmKaufmann,
    MarieLaursen,
    FlavioNieves,
    PeterBelousov,
    KlimekMichalski,
    SantiagoMoreno,
    BenjaminCoppens,
    NoahVisser,
    GertWaldmuller,
    JulianQuesada,
    DanielJones,
    ArtemMarkelov,
    TadasukeMakino,
    SeanGelael,
    NyckDeVries,
    JackAitken,
    GeorgeRussell,
    MaximilianGunther,
    NireiFukuzumi,
    LucaGhiotto,
    LandoNorris,
    SergioSetteCamara,
    LouisDeletraz,
    AntonioFuoco,
    CharlesLeclerc,
    PierreGasly,
    AlexanderAlbon,
    NicholasLatifi,
    DorianBoccolacci,
    NikoKari,
    RobertoMerhi,
    ArjunMaini,
    AlessioLorandi,
    RubenMeijer,
    RashidNair,
    JackTremblay,
    AntonioGiovinazzi,
    RobertKubica,
    NobuharuMatsushita,
    NikitaMazepin,
    GuanyaZhou,
    MickSchumacher,
    CallumIlott,
    JuanManuelCorrea,
    JordanKing,
    MahaveerRaghunathan,
    TatianaCalderon,
    AnthoineHubert,
    GuilianoAlesi,
    RalphBoschung,
    DevonButler,
    LukasWebber,
    Player,
    Unknown,
}

impl Driver {
    pub fn name(self) -> &'static str {
        match self {
            Driver::CarlosSainz => "Carlos Sainz",
            Driver::DaniilKvyat => "Daniil Kvyat",
            Driver::DanielRicciardo => "Daniel Ricciardo",
            Driver::KimiRaikkonen => "Kimi Raikkonen",
            Driver::LewisHamilton => "Lewis Hamilton",
            Driver::MaxVerstappen => "Max Verstappen",
            Driver::NicoHulkenburg => "Nico Hulkenberg",
            Driver::RomainGrosjean => "Romain Grosjean",
            Driver::KevinMagnussen => "Kevin Magnussen",
            Driver::SebastianVettel => "Sebastian Vettel",
            Driver::SergioPerez => "Sergio Perez",
            Driver::ValtteriBottas => "Valtteri Bottas",
            Driver::EstebanOcon => "Esteban Ocon",
            Driver::LanceStroll => "Lance Stroll",
            Driver::CharlesLeclerc => "Charles Leclerc",
            Driver::LandoNorris => "Lando Norris",
            Driver::AlexanderAlbon => "Alexander Albon",
            Driver::PierreGasly => "Pierre Gasly",
            Driver::GeorgeRussell => "George Russell",
            Driver::NicholasLatifi => "Nicholas Latifi",
            Driver::AntonioGiovinazzi => "Antonio Giovinazzi",
            Driver::MickSchumacher => "Mick Schumacher",
            Driver::CallumIlott => "Callum Ilott",
            Driver::AnthoineHubert => "Anthoine Hubert",
            Driver::RobertKubica => "Robert Kubica",
            Driver::GuanyaZhou => "Guanya Zhou",
            Driver::Player => "Player",
            _ => "[N/A]",
        }
    }
}
